---
title: "compare-bias"
format: html
editor: visual
---

```{r}
library(dplyr)
library(sf)
library(ggplot2)
library(tmap)
library(viridis)

library(sysfonts)
library(showtextdb)

library(classInt)

library(scales)

library(forcats)
```

# Set themes

```{r}
#| include = FALSE
source("./style/data-visualisation_theme.R")
```

# Data import

## Census and boundaries

```{r}
wd <- dirname(getwd())
```

```{r}
df <- read.csv(paste0(wd, "/outputs/manuscript-figures/Fig-comparison-surveys/Table-comparison-surveys.csv"))
```

```{r}
df <- df %>% filter(!is.na(Size_bias))
df <- df %>% select(c(Data_source, Size_bias))
```

```{r}
ggplot(df, aes(x = reorder(Data_source, 1-Size_bias), y = Size_bias)) +
  geom_col(fill = "#69b3a2", width = 0.8) + 
  # coord_cartesian(ylim= c(0.9,1)) +
  labs(x = "Size of bias", y = "Data source") +  
  theme_plot_tufte() +  
  coord_flip(ylim=c(0.80,1)) + 
  theme(
    axis.title.x = element_text(size = 14, face = "bold", color = "black"),  
    axis.title.y = element_text(size = 14, face = "bold", color = "black"),  
    axis.text = element_text(size = 12, color = "black"),  # Adjust axis text size and color
    plot.margin = margin(10, 10, 10, 10)  # Add margins for a bit of space around the plot
  )                 
  

```
